### ISSUE TITLE
Mod crashes in modpack and isolated (1.19.2, Fabric)

### ISSUE THREAD

**Issue by InfernusIgnitus** [MrCrayfish/Backpacked#160] opened 2023-06-30 21:13 UTC
I am making a modpack with Cobblemon and some other mods in it for my friends and I to use, and having a backpack mod is something we really want to add to complete the experience. After adding the official fabric port of the mod the modpack crashes on startup, and after investigating the mod seems to crash on my system isolated as well. As per my correspondence on discord, I have crash reports here:
Modpack:
https://pastebin.com/48uqXAhJ
Isolated:
https://pastebin.com/GviDK9fA

**Comment by InfernusIgnitus** [comment] 2023-07-03 03:37
I was able to backdate Framework to get the mod to work, using 0.6.0 let it launch and play without issue!

**Comment by MrCrayfish** [comment] 2023-08-08 14:54
It was caused by Framework. Should be fixed if you install a newer version

**Closed as completed by MrCrayfish** 2023-08-08 14:54 UTC
