### ISSUE TITLE
Backpack reset for no reason

### ISSUE THREAD

**Issue by Flouffy** [MrCrayfish/Backpacked#110] opened 2022-04-24 09:16 UTC
So..the title say everythings, on my mc server (aternos), the backpack reset randomly for no reason (the backpack inventory).

**Comment by damondanerd** [comment] 2022-05-10 20:34
This happened to myself and others in my server. Not sure what the cause is. Playing the mod through Better Minecraft Modpack 1.18.2

**Comment by MrCrayfish** [comment] 2022-05-11 05:08
Describe what happened before and after it occured? Random is unlikely the issue.

**Comment by Flouffy** [comment] 2022-05-12 16:43
It happend very randomly, nothing seems to reset it, it happend 5 or 7 times in different context, the first time it happend  i died (keepinventory enable, with Configured the keepinventory for the backpack is also enable) and when i opened my backpack: nothing, i lost a lot of stuff.
The last time it happend i just /gamemode creative cause i lost my stuff again, i put AGAIN the stuff I lost (and give to myself) into the backpack and when I /gamemode survival; it reset.

**Comment by Spongman** [comment] 2022-06-14 20:47
same happened to me. moving the backback in creative mode cleared its contents.

**Comment by MrCrayfish** [comment] 2022-06-15 07:45
Can you tell me the steps to reproduce the issue? Also not sure what you mean by moving.

**Comment by Spongman** [comment] 2022-06-15 07:48
I was playing the better Minecraft modpack. I died, then went and found my body in creative mode, then transferred all the items out of it (including the backpack) then put the backpack in its bauble slot. I might have switched back to survival at that point, don’t remember, but shortly after that I opened the backpack and it was empty.

**Comment by MrCrayfish** [comment] 2022-06-15 12:26
Is everyone here using Better Minecraft modpack? I tested and managed to get the bug from the corpse (the backpack on the Corpse had no NBT). Strangely the corpse also duplicated the backpack with the second time interacting with the corpse it had the backpack with the NBT on it. I unfortunately can't get the bug to happen again as it's rare, however the corpse mod is logging "unknown packet" errors from it's own mod (which could be related). It's unlikely the issue is from my mod since everyone keeps mentioning it happens on Better Minecraft modpack.

**Closed as completed by MrCrayfish** 2022-06-15 12:26 UTC
