### ISSUE TITLE
Crash clicking on mod in mods menu

### ISSUE THREAD

**Issue by Dminty87** [MrCrayfish/Backpacked#7] opened 2020-01-30 02:27 UTC
[crash-2020-01-29_18.20.57-client.txt](https://github.com/MrCrayfish/Backpacked/files/4131866/crash-2020-01-29_18.20.57-client.txt)

Minecraft said:  The game crashed whilst mouseclicked event handler
Error: java.lang.ArrayIndexOutOfBoundsException: 0

**Comment by MrCrayfish** [comment] 2020-02-03 06:53
Duplicate of #3

**Closed as completed by MrCrayfish** 2020-02-03 06:53 UTC
