### ISSUE TITLE
Backpacked fabric crash on server

### ISSUE THREAD

**Issue by ianm1647** [MrCrayfish/Backpacked#150] opened 2023-04-24 18:54 UTC
Minecraft Version: 1.19.4
Fabric Version: 0.14.19
Fabric API Version: 0.79.0
Framework Version: 0.6.4
Backpacked Version: 2.2.0

The server doesn't crash, just the client. I do have a backpack on and that's when the crashes started happening, I'm not sure if its an incompatibility with Immersive Portals or not but here's the [crash log](https://pastebin.com/ZCiFa8DH). It also seems to bring up the Framework API , so it could be something there as well.

**Comment by MrCrayfish** [comment] 2023-08-08 14:54
It was caused by Framework. Should be fixed if you install a newer version

**Closed as completed by MrCrayfish** 2023-08-08 14:54 UTC
