### ISSUE TITLE
Backpacked 1.8.0 Crash in Forge 1.16.5

### ISSUE THREAD

**Issue by Assasingus14** [MrCrayfish/Backpacked#42] opened 2021-03-06 03:52 UTC
I tried to load this mod for a modpack on my server and got this crash

[crash-2021-03-06_03.49.44-fml.txt](https://github.com/MrCrayfish/Backpacked/files/6094631/crash-2021-03-06_03.49.44-fml.txt)

I am using the Blame mod too, to help point me out any crash issues

**Comment by MrCrayfish** [comment] 2021-03-06 03:56
Duplicate of https://github.com/MrCrayfish/Backpacked/issues/40
Update to 1.8.1

**Closed as completed by MrCrayfish** 2021-03-06 03:56 UTC
