### ISSUE TITLE
[Forge/1.20.1]Key 'open backpack' not listed in controls menu

### ISSUE THREAD

**Issue by Sto3IV** [MrCrayfish/Backpacked#186] opened 2024-01-18 10:54 UTC
Steps to reproduce:
1. Install 1.20.1
2. Install ANY forge for 1.20.1.
3. Install ANY framework mod and Curios for 1.20.1.
4. Install ANY version of backpacked for 1.20.1.
5. Go to controls tab.
???
NO WAY THE KEY IS MISSING
Additional steps:
6. Give up.
7. Try to add key_key.backpack:key.keyboard.o from 1.19.4 to 1.20.1 options.txt
8. Restart Minecraft
9. The key is still missing.
10. Give up.
![image](https://github.com/MrCrayfish/Backpacked/assets/5441212/5abaa402-a73b-4d40-b135-0b1dd425b40b)
![image](https://github.com/MrCrayfish/Backpacked/assets/5441212/5db0909a-f730-44ce-a802-ff5082f0b30e)

**Comment by IdrisQe** [comment] 2024-01-23 04:30
Duplicate of https://github.com/MrCrayfish/Backpacked/issues/178, but experiencing the same issue here.

**Comment by Sto3IV** [comment] 2024-01-23 06:13
Try to add key_key.backpack:key.keyboard.o from 1.19.4 to 1.20.1 options.txt
Restart Minecraft
The key is still missing.

______
So it didn't help.

**Closed as completed** 2024-01-30 07:05 UTC
